# Generated by Django 5.1.4 on 2024-12-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('description', models.TextField(default="Avtor ma'lumot qoshmadi:)", verbose_name='Tavsifi')),
                ('price', models.IntegerField(default=0, verbose_name='Narxi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqti')),
                ('published', models.BooleanField(default=True, help_text='Agar bu yerda - "False" bolsa bu gul sotuvda korinmaydi, Agar "True" bolsa korinadi', verbose_name='Qoshilganligi')),
                ('views', models.IntegerField(default=0, verbose_name='Korishlar soni')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-id'],
            },
        ),
    ]
